platform :ios, '9.0'

target 'PokedexGo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift',    '~> 3.0.0-beta.1'
  pod 'RxCocoa',    '~> 3.0.0-beta.1'

end
